[package]
name = "tpi"
version = "1.0.5"
edition = "2021"
license = "Apache-2.0"
authors = ["Sven Rademakers <sven@turingpi.com>", "Ruslan Akbashev <ra@turingpi.com>"]
description = "Official Turing-Pi2 CLI tool"
homepage = "https://turingpi.com/"
repository = "https://github.com/turing-machines/tpi"
readme = "README.md"
categories= ["command-line-interface"]
keywords= ["turing-pi", "tpi", "CLI", "edge-computing", "board-management"]
exclude = [".github", "deny.toml", "scripts/ci/*"]

[dependencies]
anyhow = "1.0.79"
bytes = "1.5.0"
clap = { version = "4.4.18", features = ["derive", "wrap_help", "env"] }
clap_complete = "4.4.9"
crossterm = "=0.24.0"
dirs = "5.0.1"
indicatif = { version = "0.17.7", features = ["tokio"] }
platform-info = "2.0.2"
reqwest = { version = "0.11.23", default-features = false, features = ["gzip", "json", "multipart", "stream"] }
serde_json = "1.0.113"
tokio = { version = "1.35.1", features = ["rt", "rt-multi-thread", "macros", "fs"] }
tokio-util = "0.7.10"
url = "2.5.0"

[features]
default = ["reqwest/rustls-tls"]
native-tls = ["reqwest/native-tls"]
localhost = []
